version: '3.8'

services:
  clean-architecture-api:
    image: clean-architecture-api:latest
    build:
      context: .
      dockerfile: ./src/Clean.Architecture.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
